
"use strict";

const CONFIG_WIDTH = 1400
const CONFIG_HEIGHT = 800
const CONFIG_BLOCK = 40

const GAME_STATE_MAIN_MENU = 1
const GAME_STATE_BUY = 2
const GAME_STATE_COMBAT = 3
const GAME_STATE_WIN = 4

const PLAYER_BLUE = 1
const PLAYER_RED = 2

const AI_PLAYER = 1
const AI_NORMAL = 2
const AI_DIFFICULT = 3

const CONFIG_COMBAT_LEN = 10
const CONFIG_MAX_SPAWN = 5
